# Generated by Django 5.2.14 on 2026-05-27 04:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('employer', 'Employer / Industry Partner'), ('officer', 'Placement Officer'), ('supervisor', 'Academic Supervisor')], default='student', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('abn', models.CharField(blank=True, default='', max_length=20)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_done', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('skills', models.TextField(blank=True, default='')),
                ('stipend', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('work_type', models.CharField(blank=True, choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], default='', max_length=20)),
                ('start_date', models.CharField(blank=True, default='', max_length=100)),
                ('end_date', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_internships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(choices=[('Employer', 'Employer'), ('Academic Supervisor', 'Academic Supervisor')], max_length=30)),
                ('rating_conduct', models.IntegerField(default=3)),
                ('rating_technical', models.IntegerField(default=3)),
                ('rating_communication', models.IntegerField(default=3)),
                ('rating_overall', models.IntegerField(default=3)),
                ('comments', models.TextField(blank=True, default='')),
                ('recommendation', models.CharField(blank=True, default='', max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='iipms_app.internship')),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions_recorded', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='completions', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='iipms_app.internship')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('stipend', models.CharField(blank=True, default='', max_length=100)),
                ('terms', models.TextField(blank=True, default='')),
                ('officer_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Awaiting Officer Approval', 'Awaiting Officer Approval'), ('Awaiting Student Acceptance', 'Awaiting Student Acceptance'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Rejected by Officer', 'Rejected by Officer')], default='Awaiting Officer Approval', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offers', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='offers_sent', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='iipms_app.internship')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='offers_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Placed', 'Placed'), ('Withdrawn', 'Withdrawn'), ('Completed', 'Completed')], max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='iipms_app.internship')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries_set', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, default='', max_length=200)),
                ('wam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('availability', models.CharField(blank=True, default='', max_length=100)),
                ('skills', models.TextField(blank=True, default='')),
                ('industry_pref', models.CharField(blank=True, choices=[('', 'No preference'), ('Technology', 'Technology / IT'), ('Finance', 'Finance / Banking'), ('Healthcare', 'Healthcare'), ('Engineering', 'Engineering'), ('Marketing', 'Marketing'), ('Education', 'Education'), ('Any', 'Open to Any')], default='', max_length=50)),
                ('work_type', models.CharField(blank=True, choices=[('', 'No preference'), ('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid'), ('Any', 'No preference')], default='', max_length=20)),
                ('location_pref', models.CharField(blank=True, default='', max_length=100)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('is_eligible', models.BooleanField(default=False)),
                ('has_work_rights', models.BooleanField(default=True)),
                ('eligibility_notes', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, default='', max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=200)),
                ('week_number', models.PositiveIntegerField()),
                ('hours_worked', models.PositiveIntegerField()),
                ('tasks', models.TextField()),
                ('challenges', models.TextField(blank=True, default='')),
                ('reflection', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to='iipms_app.internship')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Interview Scheduled', 'Interview Scheduled'), ('Shortlisted', 'Shortlisted'), ('Reference Check', 'Reference Check'), ('Offer Extended', 'Offer Extended'), ('Hired', 'Hired'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=30)),
                ('interview_date', models.CharField(blank=True, default='', max_length=100)),
                ('interview_note', models.TextField(blank=True, default='')),
                ('student_response', models.CharField(blank=True, choices=[('', 'No response yet'), ('Accepted Interview', 'Accepted Interview'), ('Declined Interview', 'Declined Interview'), ('Accepted Offer', 'Accepted Offer'), ('Declined Offer', 'Declined Offer')], default='', max_length=30)),
                ('officer_next_step', models.CharField(blank=True, default='', max_length=200)),
                ('officer_note', models.TextField(blank=True, default='')),
                ('skills_at_apply', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='iipms_app.internship')),
            ],
            options={
                'unique_together': {('student', 'internship')},
            },
        ),
        migrations.CreateModel(
            name='SupervisorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_assignments', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'supervisor')},
            },
        ),
    ]
